### PR TITLE
Fixed the inverted/reverse chat nature

### PR DESCRIPTION
**Pull request by funjay**
issue  #51

### CODE REVIEW

**Comment by SebastienBtr** [comment]
I won't add this feature, it's adding too much complexity (there are way more changes than that to make it work properly) for something that isn't needed. The order of the chats is controlled by the order of your data, if the messages don't show up in your desired order you can simply reverse your list of messages. Dashchat has been made to put older messages at the top and the latest messages at the bottom, as shown in all examples. This is the behavior of all chat apps that I know, therefore I don't see any need to have it the other way around

**Comment by funjay** [comment]
I Tried with the example and the latest messages was placed on the top , my screen shot  shows it, i can do a video for you. Or do you want me to give you my setup? 

it might be a bug, but after digging i saw that in the ListView.builder under message_list.dart has **reverse set to true**, a quick google will tell that it turns it the other way round, the default is false but dash_chat makes it true. 

The example all have same date and you dont know which is the latest,, try changing one or two messages to more recent date and messages, i did it in the issue i raised and it was putting the latest messages up. I had a screenshot or didnt you see the screen shot?

You can try it yourself and make changes to the date so you can really isolate latest messages, i can do a video with a new build for you to see, ignoring without taking a look is not good

or try explaining why there is **reverse: true** under listview.builder for message_list.dart.  What is the intention of reverse:true what do you intend to get?
https://api.flutter.dev/flutter/widgets/ScrollView/reverse.html

from the official documentation 
`Similarly, if [scrollDirection](https://api.flutter.dev/flutter/widgets/ScrollView/scrollDirection.html) is [Axis.vertical](https://api.flutter.dev/flutter/painting/Axis.html), then the scroll view scrolls from top to bottom when [reverse](https://api.flutter.dev/flutter/widgets/ScrollView/reverse.html) is false and from bottom to top when [reverse](https://api.flutter.dev/flutter/widgets/ScrollView/reverse.html) is true.

Defaults to false.`

You can consider it a bug if the intention was from top to bottom

**Comment by SebastienBtr** [comment]
`my screen shot shows it`
Your screenshot is clearly not the design of the example project, otherwise, it'd look like the screenshot in the readme

`message_list.dart has reverse set to true`
Yes it's `true` on purpose to have the list in the right order.
Because when you fetch your messages from your db with an order by timestamp descending, you'll get your messages like that: [latestMessage, ..., oldestMessage]
So of course the ListView needs to be reversed if we want to show the latest messages at the bottom and not at the top.
As I explained in my first message, you're probably providing your list of messages in the wrong order: [oldestMessage, ..., latestMessage]

This is not DashChat responsibility to sort the list of messages you're passing, if you sort/fetch them correctly it'll show the newest message at the bottom.
You can also try in the example project to send a message and you'll see that it'll appear at the bottom because the send message function provided in the readme and in all the examples are inserting the message at index 0
You obviously didn't run the example project and that'd be the first thing you should do

**Comment by funjay** [comment]
I ran the example and it was adding new messages up.. i added a video for you to see.

Yes it's true on purpose to have the list in the right order.  ** is the order new messages at the top?**
Because when you fetch your messages from your db with an order by timestamp descending, you'll get your messages like that: [latestMessage, ..., oldestMessage]  - The documentation didnt ask for sorting messages, and moreover looking at the video, without the back end it also adds new messages to the top. Do you sort every added message? 

i think you didnt run the example or maybe our flutter details are different
here is my flutter doc

`[✓] Flutter (Channel stable, 3.10.0, on Fedora Linux 38 (Workstation Edition) 6.2.14-300.fc38.x86_64, locale en_IE.UTF-8)
    • Flutter version 3.10.0 on channel stable at /home/delaw/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (5 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/delaw/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/delaw/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.0
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/delaw/opt/android-studio
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.2.14-300.fc38.x86_64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 113.0.5672.63

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.`
[Screencast from 2023-05-14 17-30-18.webm](https://github.com/SebastienBtr/Dash-Chat-2/assets/66911451/f0901838-bb8d-4c61-973c-0faf482292cd)

**Comment by funjay** [comment]
message_list.dart has reverse set to true
Yes it's true on purpose to have the list in the right order.

So the right other is top is bottom, looking at the example you do 
messages.insert(0, mess)  this ensures new messages are at index 0, that is the top of the list, mine is the bottom of the list, new messages should be at the bottom of the list IMHO
In my code i use 
messages.add(newmess)  , this will append it to the last index of the list and it is more readable
IMHO, the first message should be the oldest and should be at the top, while the latest should be the last and should be in the bottom, if you use ID that is incremental, then the grater number is the newest. 

if you feel this is not a needed feature to allow users able to change top to bottom or bottom to top , then i am fine. 
also add to the documentation that you must order the message in desc order by createdAt.

**Pull request closed without merging**
