### PR TITLE
Update chat_message.dart

### PR DESCRIPTION
**Pull request by funjay**
issue71
#71 

Adding Message status like 'failed and sent'

### CODE REVIEW

**Comment by SebastienBtr** [comment]
In my opinion, the status "sent" is not needed because you already have "pending" and "received". How would you describe the status "sent" compared to "pending"/"received" ?

**Comment by funjay** [comment]
Message sataus is not for receiver but for the sender 

Pending - message left your phone but is pending ( no update yet)
Sent - message got to the backend
Received,  - message got to the receivers phone
Read - message is opened by receiver
Failed - message left your phone but didnt get to the back end

This is more practical,. anyone can make his or her logic with these.

**Review by SebastienBtr — APPROVED** [review]

**Comment by SebastienBtr** [comment]
Okay sounds good :)

**Comment by SebastienBtr** [comment]
Thanks for your contribution 🎉

@all-contributors please add @funjay  for code

This PR closes #71

**Pull request merged**
